version: "2"
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus-msa
    ports:
      - "3018:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    restart: always
    # 도커 내부에서 호스트 포트 접속시 임시 설정용
    # 호스트 네트워크 사용시는 ports 꺼둘것(도커 내부 네트워크를 사용하지않아 포워딩 오류 발생)
    networks:
      ecomm:

  grafana:
    image: "grafana/grafana"
    container_name: grafana-msa
    ports:
      - "3017:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_DOMAIN=localhost
      - GF_SERVER_HTTP_PORT=3000
    restart: always
    volumes:
      - ./datasources:/etc/grafana/provisioning/datasources
    depends_on:
      - prometheus
    privileged: true
    networks:
      ecomm:

networks:
  ecomm:
    external: true
    name: ecommerce-network
