version: '2'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus-msa
    ports:
      - "3018:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always
    networks:
      - default

  grafana:
    image: "grafana/grafana"
    container_name: grafana-msa
    ports:
      - "3017:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_DOMAIN=localhost
      - GF_SERVER_HTTP_PORT=3000
    restart: always
    depends_on:
      - prometheus
    privileged: true
    networks:
      - default

networks:
  default:
    name: msa-project